NetSepio/gateway

- .gitignore
- .gitpod.yml
- README.md
- api/v1/feedback/feedback.go
- api/v1/feedback/feedback_test.go
- api/v1/feedback/types.go
- config/dbconfig/dbconfig.go
- go.mod
- models/Feedback.go
- models/User.go
- tmp/build-errors.log
> Add rating parameter

- .dockerignore
- .env-sample
- .gitignore
- .gitpod.Dockerfile
- .gitpod.yml
- Dockerfile
- README.md
- api/v1/delegateReviewCreation/delegateReviewCreation.go
- api/v1/delegateReviewCreation/txresult.go
- api/v1/delegateReviewCreation/types.go
- docker-start.sh
- go.mod
- util/pkg/cryptosign/checksign.go
> submit review api

- api/v1/v1.go
- api/v1/waitlist/type.go
- api/v1/waitlist/waitlist.go
- config/dbconfig/dbconfig.go
- models/WaitList.go
> Introduce waitlist api

- api/v1/delegateReviewCreation/delegateReviewCreation.go
> Return status conflict for duplicate metadata

- api/middleware/auth/paseto/paseto.go
- api/v1/delegateReviewCreation/delegateReviewCreation.go
- api/v1/delegateReviewCreation/delegateartifactcreation_test.go
- api/v1/delegateReviewCreation/types.go
> delegate review: take voter address from auth token

- api/v1/delegateReviewCreation/delegateReviewCreation.go
- api/v1/deletereview/deleteReview.go
- api/v1/deletereview/types.go
- api/v1/v1.go
- models/Review.go
- util/pkg/aptos/smartcontract.go
> Introduce delete review api

- api/v1/delegateReviewCreation/delegateReviewCreation.go
- api/v1/delegateReviewCreation/types.go
- api/v1/getreviews/types.go
- api/v1/stats/type.go
> Use http_url tag for validation

- api/middleware/auth/paseto/paseto_test.go
- api/v1/feedback/feedback.go
- api/v1/waitlist/waitlist.go
- main.go
- models/claims/Claim.go
- util/pkg/cryptosign/checksign.go
- util/pkg/flowid/flowid.go
- util/testingcommon/common.go
> Use Equal fold and lower case wallet address

- api/v1/delegateReviewCreation/delegateReviewCreation.go
- app/routines/webreview/webreview.go
> Update ipfs hash in db after archive

- api/v1/getreviews/reviews.go
- api/v1/getreviews/types.go
- docker-compose.yml
> all reviews and pagination

- .github/workflows/deploy-aws.yml
> Automated deployment

- api/v1/getreviews/reviews.go
- api/v1/getreviews/types.go
> get review: add domain to query

- api/v1/profile/profile.go
- api/v1/profile/types.go
- models/User.go
> Add discord and twitter to user profile

- api/middleware/auth/paseto/paseto.go
> Use Bearer prefix for validation

- api/v1/getreviewerdetails/reviewerdetails.go
- api/v1/getreviewerdetails/types.go
- api/v1/v1.go
> Get reviewer details

- api/v1/getreviewerdetails/reviewerdetails.go
- api/v1/getreviewerdetails/types.go
> get reviewer details: add discord and twitter

- Dockerfile
- app/routines/webreview/types.go
- app/routines/webreview/webreview.go
> Use debian for chromium support

- api/v1/stats/stats.go
- api/v1/stats/type.go
> get stats: Add domain query

- api/v1/domain/create.go
- api/v1/domain/domain.go
- api/v1/domain/query.go
- api/v1/domain/type.go
- api/v1/domain/verify.go
- api/v1/getreviews/reviews.go
- api/v1/v1.go
- config/dbconfig/dbconfig.go
- models/Domain.go
> Introduce create, query and verify apis for domain

- api/v1/domain/query.go
- api/v1/domain/type.go
> domains: query `domain` -> `domainName`

- api/v1/domain/create.go
- api/v1/domain/delete.go
- api/v1/domain/domain.go
- api/v1/domain/type.go
> Introduce delete api

- api/v1/domain/create.go
- api/v1/domain/type.go
- models/Domain.go
> domain: add chain

- api/v1/sotreus/sotreus.go
some requests even with errors weren't detected
> api/sotreus: check status code of internal request

- api/v1/domain/domain.go
- api/v1/domain/patch.go
- api/v1/domain/type.go
> Introduce api to update domain

- .gitpod.Dockerfile
- api/middleware/auth/paseto/paseto.go
- api/middleware/auth/paseto/paseto_test.go
- api/v1/authenticate/authenticate.go
- api/v1/domain/admin/create.go
- api/v1/domain/admin/delete.go
- api/v1/domain/admin/query.go
- api/v1/domain/create.go
- api/v1/domain/patch.go
- api/v1/domain/query.go
- api/v1/feedback/feedback.go
- api/v1/profile/profile.go
- config/dbconfig/dbconfig.go
- main.go
- migrations/000001_create_initial_tables.up.sql
- migrations/000002_add_user_id.up.sql
- migrations/000003_admin_domains.up.sql
- migrations/000004_domains.up.sql
- migrations/000005_feedback.up.sql
- migrations/000006_flow_id.up.sql
- migrations/000007_users_finish.up.sql
- models/Domain.go
- models/Feedback.go
- models/FlowId.go
- models/User.go
- models/claims/Claim.go
- util/pkg/cryptosign/checksign.go
- util/pkg/flowid/flowid.go
- util/testingcommon/common.go
> Introduce migrations and user id.

- api/v1/siteinsights/scrap_web.go
- api/v1/siteinsights/siteinsights.go
- api/v1/v1.go
- config/envconfig/envconfig.go
- migrations/000011_site_insight.up.sql
- models/SiteInsight.go
- util/pkg/openai/openai.go
> Introduce API to get insight of website using OpenAI

- api/v1/domain/claim/claim.go
- api/v1/domain/claim/finish.go
- api/v1/domain/claim/start.go
- api/v1/domain/claim/type.go
- api/v1/domain/domain.go
- api/v1/domain/query.go
- api/v1/domain/type.go
- migrations/000013_add_claim_txt.up.sql
- models/ClaimTxt.go
- models/Domain.go
> Introduce claim domain apis

- util/pkg/openai/openai.go
> Limit summary result to 350 chars

- util/pkg/openai/openai.go
> Improve spam filter

- api/v1/authenticate/authenticate.go
- api/v1/authenticate/types.go
- go.mod
- go.sum
- util/pkg/cryptosign/checksign.go
Gets the public key from signature and matches it with provided key, checks obtained wallet address from public key to address in db
> authenticate: add sui signature check

- api/v1/sdkauthentication/paseto_v1.go
- api/v1/v1.go
- app/app.go
- config/envconfig/envconfig.go
- go.mod
- go.sum
- models/Migrate/migrate_models.go
added paseto token api for sdk
> Merging main with prod

- api/v1/nftcontract/nftcontract.go
- models/Migrate/migrate_models.go
- models/NftSubscription.go
> add get function in nft subscription

- api/v1/dvpnnft/dvpnnft.go
- config/dbconfig/dbconfig.go
- models/DVPNNFTRecord.go
- models/Migrate/migrate_models.go
Dvpnnft 
aptos  registration added
> Merging main with prod 

- api/v1/account/auth-google.go
- api/v1/profile/profile.go
- api/v1/profile/types.go
- models/Migrate/migrate_models.go
- models/User.go
`diff: updated profile API to support Google, Apple, Telegram, and Farcaster social media platforms, removed Twitter support`
> `feat: updated profile API to support additional social media platforms`
